### ISSUE TITLE
Not able to install in Windows, not finding v6.3.0-node-v72-win32-ia32.tar.gz 

### ISSUE THREAD

**Issue by egachi** [hyj1991/v8-profiler-node8#26]
Is there a way to include ia32 repositories? 

**node-pre-gyp WARN Tried to download(404): https://github.com/hyj1991/v8-profiler-node8/releases/download/v6.3.0/profiler-v6.3.0-node-v72-win32-ia32.tar.gz** 

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/hyj1991/v8-profiler-node8/releases/download/v6.3.0/profiler-v6.3.0-node-v64-win32-ia32.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for v8-profiler-node8@6.3.0 and node@10.15.2 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  profiler.cc
d:\local\userprofile\.node-gyp\10.15.2\include\node\v8.h(21): fatal error C1083: Cannot open include file: 'memory': No such file or directory [D:\home\site\wwwroot\node_modules\v8-profiler-node8\build\profiler.vcxproj]
  cpu_profiler.cc
D:\local\UserProfile\.node-gyp\10.15.2\include\node\v8-profiler.h(8): fatal error C1083: Cannot open include file: 'unordered_set': No such file or directory [D:\home\site\wwwroot\node_modules\v8-profiler-node8\build\profiler.vcxproj]
  cpu_profile.cc

Thanks

**Comment by Widdershin** [comment]
I can’t speak to releasing new binaries but are you able to install the ‘windows-build-tool’ package?

From an admin powershell (or equivalent), run ‘ npm install --global windows-build-tools’. This will install the requisite tools to build native modules.

**Comment by hyj1991** [comment]
I don’t have an `ia32` machine, so the pre-build binary for win10 only releases `x64`, you may need to compile locally :)

**Comment by Widdershin** [comment]
For reference, I got 32bit Windows binaries building for another project using Appveyor.

The key was passing target arch to `node-pre-gyp`:

`"build-binary-x86": "node-pre-gyp rebuild --target_arch=ia32 && node-pre-gyp package --target_arch=ia32"`

Appveyor config here: https://github.com/Widdershin/mmap-io/blob/master/appveyor.yml

It's worth noting that the `Platform` flag on Appveyor doesn't actually control the underlying VM architecture, it just sets flags to enable 32bit compilation for .NET apps. In this example I'm just using it since it's a convenient way to split out the builds.
