### ISSUE TITLE
v8-profiler-node8 or v8-profiler-next

### ISSUE THREAD

**Issue by shuhei** [hyj1991/v8-profiler-node8#5]
Hi, thank a lot for your awesome work!

I am wondering which of `v8-profiler-node8` and `v8-profiler-next` is recommended to use. `v8-profiler-node8` was updated more recently, but the name of `v8-profiler-next` sounds newer.

Which one would you recommend? Or were they built for different purposes?

**Comment by hyj1991** [comment]
`v8-profiler-next` has a new feature: **sampling heap profile**, and `v8-profiler-node8` is totally based on [v8-profiler](https://github.com/node-inspector/v8-profiler) (I create this project because they don't maintain v8-profiler anymore)

I recommend using `v8-profiler-node8` because **sampling heap profile** isn't stable now :)

**Comment by shuhei** [comment]
@hyj1991 Thanks a lot for clarification! I’ll use `v8-profiler-node8` for now. Also looking forward to seeing `v8-profiler-next` stabilised!

**Comment by hyj1991** [comment]
@shuhei now you can try [v8-profiler-next](https://www.npmjs.com/package/v8-profiler-next) because I found that getting heap snapshots and sample heap configuration files in 12.x at the same time no longer crashes.
